#pragma once
void read_test_INCORRECT_PARAMETERS_ERROR1();
void read_test_INCORRECT_PARAMETERS_ERROR2();
void read_test_INCORRECT_PARAMETERS_ERROR3();
void read_test_INCORRECT_PARAMETERS_ERROR4();
void read_test_INCORRECT_PARAMETERS_ERROR5();
void read_test_UNKNOWN_ERROR();
void read_test_OUT_OF_BOUNDS_ERROR();
void read_test_SUCCESSFUL_IMPLEMENTATION1();
void read_test_SUCCESSFUL_IMPLEMENTATION2();
void read_all_tests();