#pragma once
void write_test_INCORRECT_PARAMETERS_ERROR1();
void write_test_INCORRECT_PARAMETERS_ERROR2();
void write_test_INCORRECT_PARAMETERS_ERROR3();
void write_test_INCORRECT_PARAMETERS_ERROR4();
void write_test_INCORRECT_PARAMETERS_ERROR5();
void write_test_UNKNOWN_ERROR();
void write_test_OUT_OF_BOUNDS_ERROR();
void write_test_SUCCESSFUL_IMPLEMENTATION1();
void write_test_SUCCESSFUL_IMPLEMENTATION2();
void write_all_tests();